name: workano-otp-playback
namespace: official
version: 0.0.1
author: Shahrooz.Bazrsfahan@gmail.com
display_name: Workano otp playback
min_wazo_version: 19.17
tags:
  - otp
  - playback
homepage: https://workano.com